[package]
name = "ssr-perf"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
clap = { version = "3.1.17", features = ["derive"] }