[package]
name = "function_router"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lipsum = "0.8.2"
log = "0.4"
rand = { version = "0.8", features = ["small_rng"] }
yew = { version = "0.20" }
yew-router = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
gloo = "0.8"
gloo-net = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
uuid = { version = "1.5.0", features = ["serde"] }
instant = { version = "0.1", features = ["wasm-bindgen"] }
once_cell = "1"
chrono = "0.4.31"


[dependencies.web-sys]
version = "0.3.60"
features = [
    'Clipboard',
    'FocusEvent',
    'HtmlSelectElement',
    'Location',
    'MessageEvent',
    'Navigator',
    'PromiseRejectionEvent',
    'UiEvent',
    'VisibilityState',
    'Window',
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[[bin]]
name = "function_router"
required-features = ["yew/csr"]
