[package]
name = "yew_ssr_v3"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
required-features = ["hydration"]

[[bin]]
name = "simple_ssr"
required-features = ["ssr"]

[dependencies]
anyhow = { version = "1.0.57" }
getrandom = { version = "0.2.6", features = ["std", "js"] }
gloo = "0.7.0"
hyper = { version = "0.14.18", features = ["full"] }
rand = "0.8.5"
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
styled-yew = "0.3.0"
walkdir = "2.3.2"
warp = "0.3.2"
yew = { version = "0.20" }
yew-router = "0.17"
wasm-bindgen-futures = "0.4"
chrono = "0.4.31"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
num_cpus = "1.13.1"
once_cell = "1.10.0"
tokio-util = { version = "0.7.1", features = ["full"] }
clap = { version = "3.1.17", features = ["derive"] }
actix-files = "0.6.0"
tokio = { version = "1.18.2", features = ["full"] }
actix-web = "4.0.1"
reqwest = "0.11.10"
futures = "0.3.21"

[target.'cfg(unix)'.dependencies]
jemallocator = "0.5"

[dependencies.web-sys]
version = "0.3.60"
features = [
    'Clipboard',
    'FocusEvent',
    'HtmlSelectElement',
    'Location',
    'MessageEvent',
    'Navigator',
    'PromiseRejectionEvent',
    'UiEvent',
    'VisibilityState',
    'Window',
]

[features]
ssr = ["yew/ssr"]
hydration = ["yew/hydration"]